apiVersion: v1
kind: Service
metadata:
  name: employee-service-semver
spec:
  type: ClusterIP
  ports:
    - name: http-v1
      port: 80
      targetPort: 80
    - name: http-v2
      port: 8080
      targetPort: 8080
  selector:
    app: employee-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-semver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-service-container
          image: pubudu/emp:v1
          ports:
            - containerPort: 80
            - containerPort: 8080
